### ISSUE TITLE
Add flight, type of aircraft,time seen to log file.Also add an option to be able to run a cron job, but keep the press return key to refresh. 

### ISSUE THREAD

**Issue by graememilne** [dnsge/plane-spotting#1]
Hi Daniel
This is a very good piece of software.

1. Would it be possible to, Add flight, type of aircraft,time seen to a log file ???
2. The log file rotating hourly and/or daily ???
3. Also add an option to be able to run a cron job to refresh data on screen ,but keep the press return key to refresh ??? 

Regards
Graeme

**Comment by dnsge** [comment]
Hi Graeme, 

I'm not entirely sure what you want, but it sounds like logging flight radar information periodically to a file. This is certainly possible: modifying `main.py` to automatically refresh the nearby flight information every hour (or whatever interval) would be pretty close to what you're trying to achieve, I think. 

You're welcome to fork this repository to make these changes, as I don't feel they're entirely relevant to the point of this repository (an interactive nearby flight finder, not automatic and logging).
